#!/usr/bin/with-contenv bash

# parse env vars to options
OPTIONS=""
if [[ ${NZBGET_USER} && ${NZBGET_USER-x} ]]; then
  OPTIONS+="-o ControlUsername=${NZBGET_USER} "
fi
if [[ ${NZBGET_PASS} && ${NZBGET_PASS-x} ]]; then
  OPTIONS+="-o ControlPassword=${NZBGET_PASS} "
fi

exec \
    s6-setuidgid abc /app/nzbget/nzbget -s -c /config/nzbget.conf \
    -o OutputMode=log ${OPTIONS}
