#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*    This image will be deprecated on 2022-12-31.    *
*                                                    *
*                                                    *
******************************************************
******************************************************

nzbget has been deprecated by its developers.
Please consider switching to SABnzbd
https://github.com/linuxserver/docker-sabnzbd

******************************************************
******************************************************'
