#!/bin/bash
umask 000

echo "Starting nzbget daemon"
/sbin/setuser abc /app/nzbget -D -c /config/nzbget.conf
echo "Following log"
exec /sbin/setuser abc tail -F /downloads/nzbget.log --pid=$(cat /downloads/nzbget.lock)
