#!/usr/bin/with-contenv bash

# delete lock file if found
[[ -f /downloads/nzbget.lock ]] && \
	rm /downloads/nzbget.lock

# check if config file exists in /config
[[ ! -f /config/nzbget.conf ]] && \
	cp /app/nzbget/share/nzbget/nzbget.conf /config/nzbget.conf
	sed -i \
		 -e "s#\(MainDir=\).*#\1/downloads#g" \
		 -e "s#\(ScriptDir=\).*#\1$\{MainDir\}/scripts#g" \
		 -e "s#\(WebDir=\).*#\1/app/nzbget/share/nzbget/webui#g" \
		 -e "s#\(ConfigTemplate=\).*#\1/app/nzbget/share/nzbget/nzbget.conf#g" \
	/config/nzbget.conf

# permissions
chown abc:abc \
	/downloads
chown abc:abc -R \
	/app/nzbget \
	/config
chmod u+rw \
	/config/nzbget.conf
